name: incompFlow

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**.md'

jobs:         

  LidDrivenCavity:
    name: "LidDrivenCavity"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akashdhruv/Maple/.github/actions/maple
    - uses: eWaterCycle/setup-singularity@v7
    - name: Run incompFlow/LidDrivenCavity
      run: |
          sudo apt-get install -y libopenmpi-dev openmpi-bin
          cd incompFlow/LidDrivenCavity
          maple image build lidcav
          mpirun -n 1 maple container run --image=lidcav "/home/run/flashx"
